//! End-to-end extractor tests driven by real archive fixtures.
//!
//! Fixtures are committed under `tests/fixtures/` and regenerated by
//! `tests/fixtures/gen.sh`. Each test copies the fixture into a `tempfile::TempDir`
//! first so the on-disk `*_out/` artefacts never pollute the committed tree.
//!
//! These tests exercise the real extractor backends (`zip`, `sevenz`, `unar`)
//! against the `Extractor` trait, so they implicitly validate the password
//! loop, nested-child discovery, and multi-volume dispatch.

use std::fs;
use std::path::PathBuf;

use autoarc::extractors::sevenz::SevenzExtractor;
use autoarc::extractors::unar::UnarExtractor;
use autoarc::extractors::zip::ZipExtractor;
use autoarc::extractors::{ExtractOutcome, Extractor};
use autoarc::progress::{Reporter, TaskReporter};
use tempfile::TempDir;

/// Exact plaintext baked into every non-split fixture. Must match the heredoc
/// in `tests/fixtures/gen.sh` byte-for-byte.
const HELLO_TXT: &str = "\
hello from autoarc fixtures
this is plaintext used to exercise the extractor pipeline
line three
";

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Create a workspace-local tempdir under `target/test-tmp/` so the tests
/// work in sandboxed environments that deny writes to `$TMPDIR`.
fn tempdir() -> TempDir {
    let base = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/test-tmp");
    fs::create_dir_all(&base).unwrap();
    TempDir::new_in(&base).unwrap()
}

/// Copy `name` from the committed fixtures into `td` and return the new path.
fn copy_fixture(td: &TempDir, name: &str) -> PathBuf {
    let src = fixtures_dir().join(name);
    let dst = td.path().join(name);
    fs::copy(&src, &dst).unwrap_or_else(|e| panic!("copy {}: {e}", src.display()));
    dst
}

/// Build a throwaway reporter for the extractor under test. The bars render to
/// stderr; cargo test captures it unless `--nocapture` is passed.
fn reporter() -> TaskReporter {
    Reporter::new(0).task("integration")
}

// ============================================================================
// Single-layer zip
// ============================================================================

#[test]
fn zip_no_password_extracts_plaintext() {
    let td = tempdir();
    let archive = copy_fixture(&td, "single_nopass.zip");

    let outcome = ZipExtractor::try_extract(&archive, "", &reporter()).unwrap();
    assert!(
        matches!(outcome, ExtractOutcome::Success(ref c) if c.is_empty()),
        "unencrypted zip should succeed with no children",
    );

    let out = td.path().join("single_nopass.zip_out/hello.txt");
    assert_eq!(fs::read_to_string(out).unwrap(), HELLO_TXT);
}

#[test]
fn zip_with_password_rejects_empty_attempt() {
    let td = tempdir();
    let archive = copy_fixture(&td, "single_pass.zip");

    let outcome = ZipExtractor::try_extract(&archive, "", &reporter()).unwrap();
    assert!(
        matches!(outcome, ExtractOutcome::BadPassword),
        "encrypted zip must refuse the empty password",
    );
}

#[test]
fn zip_with_password_rejects_wrong_password() {
    let td = tempdir();
    let archive = copy_fixture(&td, "single_pass.zip");

    let outcome = ZipExtractor::try_extract(&archive, "not-the-password", &reporter()).unwrap();
    assert!(matches!(outcome, ExtractOutcome::BadPassword));
}

#[test]
fn zip_with_password_extracts_with_correct_password() {
    let td = tempdir();
    let archive = copy_fixture(&td, "single_pass.zip");

    let outcome = ZipExtractor::try_extract(&archive, "secret", &reporter()).unwrap();
    assert!(matches!(outcome, ExtractOutcome::Success(_)));

    let out = td.path().join("single_pass.zip_out/hello.txt");
    assert_eq!(fs::read_to_string(out).unwrap(), HELLO_TXT);
}

// ============================================================================
// Nested: outer zip("outer") wraps inner 7z("inner") wraps hello.txt
// ============================================================================

#[test]
fn nested_zip_surfaces_inner_7z_as_child() {
    let td = tempdir();
    let archive = copy_fixture(&td, "nested_pass.zip");

    // Step 1: extract the outer zip. Success must enumerate exactly one child
    // (the inner .7z) so the runner can enqueue it as the next task.
    let outcome = ZipExtractor::try_extract(&archive, "outer", &reporter()).unwrap();
    let children = match outcome {
        ExtractOutcome::Success(c) => c,
        ExtractOutcome::BadPassword => panic!("outer zip rejected 'outer' password"),
        ExtractOutcome::RetryableFailure(message) => {
            panic!("outer zip failed ambiguously: {message}")
        }
    };
    assert_eq!(
        children.len(),
        1,
        "outer zip should contain exactly inner.7z"
    );
    let inner_7z = &children[0];
    assert_eq!(inner_7z.file_name().unwrap(), "inner.7z");
    assert!(inner_7z.exists(), "inner.7z must be materialised on disk");

    // Step 2: extract the inner 7z with its own password. The plaintext should
    // end up at {tempdir}/nested_pass.zip_out/inner.7z_out/hello.txt.
    let outcome = SevenzExtractor::try_extract(inner_7z, "inner", &reporter()).unwrap();
    assert!(matches!(outcome, ExtractOutcome::Success(_)));

    let out = inner_7z.parent().unwrap().join("inner.7z_out/hello.txt");
    assert_eq!(fs::read_to_string(out).unwrap(), HELLO_TXT);
}

#[test]
fn nested_inner_rejects_outer_password() {
    // Cross-password sanity check: the inner .7z must not accept the outer
    // password, otherwise the password loop would stop too early in the
    // nested-password scenario.
    let td = tempdir();
    let outer = copy_fixture(&td, "nested_pass.zip");

    let ExtractOutcome::Success(children) =
        ZipExtractor::try_extract(&outer, "outer", &reporter()).unwrap()
    else {
        panic!("outer extraction failed");
    };
    let inner_7z = &children[0];

    let outcome = SevenzExtractor::try_extract(inner_7z, "outer", &reporter()).unwrap();
    assert!(
        matches!(outcome, ExtractOutcome::BadPassword),
        "inner 7z must not accept the outer zip's password",
    );
}

// ============================================================================
// Multi-volume 7z split (.7z.001 .. .7z.00N) dispatched through unar
// ============================================================================

#[test]
fn multi_volume_7z_extracts_via_unar() {
    let td = tempdir();
    // Copy every committed part so unar can walk the volume chain.
    for name in [
        "split.7z.001",
        "split.7z.002",
        "split.7z.003",
        "split.7z.004",
        "split.7z.005",
    ] {
        copy_fixture(&td, name);
    }
    let primary = td.path().join("split.7z.001");

    let outcome = UnarExtractor::try_extract(&primary, "", &reporter()).unwrap();
    assert!(
        matches!(outcome, ExtractOutcome::Success(_)),
        "unar must accept the multi-volume 7z and report Success",
    );

    // The complete archive name is retained, so names that differ only by
    // dots versus underscores cannot collapse onto the same output path.
    let out = td.path().join("split.7z.001_out/bigfile.bin");
    let data = fs::read(&out).unwrap_or_else(|e| panic!("read {}: {e}", out.display()));
    assert_eq!(
        data.len(),
        4096,
        "extracted payload must match the 4096-byte fixture source",
    );
}

#[test]
fn unar_never_deletes_a_preexisting_output_directory() {
    let td = tempdir();
    let primary = copy_fixture(&td, "split.7z.001");
    let outdir = td.path().join("split.7z.001_out");
    fs::create_dir(&outdir).unwrap();
    let note = outdir.join("user-note.txt");
    fs::write(&note, b"keep me").unwrap();

    let err = UnarExtractor::try_extract(&primary, "", &reporter()).unwrap_err();

    assert!(
        err.downcast_ref::<autoarc::AutoarcError>().is_some_and(
            |e| matches!(e, autoarc::AutoarcError::OutputCollision(path) if path == &outdir)
        ),
        "expected an output-collision error, got {err:#}",
    );
    assert_eq!(fs::read(note).unwrap(), b"keep me");
}

#[test]
fn failed_unar_attempt_cleans_only_its_private_staging_directory() {
    let td = tempdir();
    let primary = copy_fixture(&td, "split.7z.001");

    let outcome = UnarExtractor::try_extract(&primary, "", &reporter()).unwrap();

    assert!(
        matches!(outcome, ExtractOutcome::RetryableFailure(_)),
        "missing split volumes must remain retryable for later passwords",
    );
    assert!(!td.path().join("split.7z.001_out").exists());
    let leaked_staging = fs::read_dir(td.path())
        .unwrap()
        .filter_map(Result::ok)
        .any(|entry| {
            entry
                .file_name()
                .to_string_lossy()
                .starts_with(".autoarc-unar-")
        });
    assert!(!leaked_staging, "failed attempt leaked a staging directory");
}
